version: "3.8"

services:

  backend:
    build: ./walletmanagement
    container_name: wallet-backend
    ports:
      - "8080:8080"

  frontend:
    build: ./wallet-ui
    container_name: wallet-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend